apiVersion: batch/v1
kind: Job
metadata:
  name: qmstr
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: qmstr
    spec:
      restartPolicy: Never
      containers:
        - name: qmstr-master
          image: endocodeci/qmstr-master:sha-24bc6f4
          command: [ "sh", "-c", "sleep 40 && /usr/local/bin/qmstr-master --config /home/qmstr/config/qmstr.yaml" ]
          ports:
            - containerPort: 50051
          env:
            - name: SERVER_BUILDPATH
              value: "/var/qmstr/buildroot"
          volumeMounts:
            - name: config-volume
              mountPath: /home/qmstr/config/
            - name: buildroot-volume
              mountPath: /var/qmstr/buildroot/
        - name: dgraph
          image: dgraph/standalone:latest
        - name: fasten-reporter
          image: endocode/fasten-reporter-standalone:latest
          env:
            - name: RABBITMQ_ADDRESS
              value: "amqp://guest:guest@rabbitmq-service:5672/"
            - name: DB_ADDRESS
              value: "dgraph:9080"
            - name: REPORT_TOPIC_NAME
              value: "fasten.qmstr.out"
            - name: KAFKA_ADDRESS
              value: "fasten-kafka-instance-0.fasten-kafka-instance-headless.default.svc.cluster.local:9092"

        - name: qmstr-client
          image: endocode/qmstr-client-mvn:fasten-reporter-curl
          command: [ "sh", "-c", "sleep 60 && mvn package -Dmaven.test.skip=true && qmstrctl analyze --verbose && curl --location --request POST 'http://rabbitmq-service:15672/api/exchanges/%2f/amq.default/publish' \
                                                                                                                  --header 'Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=' \
                                                                                                                  --header 'Content-Type: text/plain' \
                                                                                                                  --data-raw '{\"properties\":{},
                                                                                                                  \"routing_key\":\"fasten-reporter\",
                                                                                                                  \"payload\":\"gooooo!!!!!\",
                                                                                                                  \"payload_encoding\":\"string\"}'" ]
          env:
            - name: QMSTRADDRENV
              value: "localhost:50051"
            - name: BUILDROOT
              value: /var/qmstr/buildroot
            - name: QMSTR_MASTER
              value: "localhost:50051"
          volumeMounts:
            - name: buildroot-volume
              mountPath: /var/qmstr/buildroot
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /buildroot" ]
          volumeMounts:
            - name: buildroot-volume
              mountPath: /buildroot
        - name: repo-clone
          image: endocodeci/git:sha-4678e1d
          command:
            - "git"
            - "clone"
          args:
            - REPOSITORY_URL
            - "/home/git/buildroot/project"
          volumeMounts:
            - name: buildroot-volume
              mountPath: /home/git/buildroot
        - name: pom-patch
          image: endocodeci/pom-patch:sha-c47d6c5
          command: [ "python", "insert-build-plugin.py", "qmstr-maven-plugin.xml" ]
          volumeMounts:
            - name: buildroot-volume
              mountPath: /home/configure/buildroot
        - name: wait-for-rabbit
          image: endocode/rabbit-poller
          env:
            - name: RABBIT_HOST
              value: "rabbitmq-service"
            - name: RABBIT_PORT
              value: "5672"
      volumes:
        - name: buildroot-volume
          emptyDir: { }
        - name: config-volume
          configMap:
            name: qmstr-config
            items:
              - key: qmstrConfig
                path: qmstr.yaml

