apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      restartPolicy: Always
      containers:
        - image: rabbitmq
          name: rabbitmq
          ports:
            - containerPort: 5672
          resources:
            limits:
              cpu: 100m
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "rabbitmq-plugins --offline enable rabbitmq_management" ]
