apiVersion: batch/v1
kind: Job
metadata:
  name: qmstr
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: qmstr
    spec:
      restartPolicy: Never
      containers:
        - name: qmstr-master
          image: endocodeci/qmstr-master:sha-086f323
          command: [ "sh", "-c", "sleep 40 && /usr/local/bin/qmstr-master --config /home/qmstr/config/qmstr.yaml" ]
          ports:
            - containerPort: 50051
          env:
            - name: SERVER_BUILDPATH
              value: "/var/qmstr/buildroot"
          volumeMounts:
            - name: config-volume
              mountPath: /home/qmstr/config/
            - name: buildroot-volume
              mountPath: /var/qmstr/buildroot/
        - name: dgraph
          image: dgraph/standalone:latest
        - name: qmstr-client
          image: endocodeci/qmstr-client-mvn:sha-086f323
          command: [ "sh", "-c", "sleep 60 && mvn package -Dmaven.test.skip=true && qmstrctl analyze --verbose" ]
          env:
            - name: QMSTRADDRENV
              value: "localhost:50051"
            - name: BUILDROOT
              value: /var/qmstr/buildroot
            - name: QMSTR_MASTER
              value: "localhost:50051"
          volumeMounts:
            - name: buildroot-volume
              mountPath: /var/qmstr/buildroot
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /buildroot" ]
          volumeMounts:
            - name: buildroot-volume
              mountPath: /buildroot
        - name: repo-clone
          image: endocodeci/git:sha-4678e1d
          command:
            - "git"
            - "clone"
          args:
            - REPOSITORY_URL
            - "/home/git/buildroot/project"
          volumeMounts:
            - name: buildroot-volume
              mountPath: /home/git/buildroot
        - name: pom-patch
          image: endocodeci/pom-patch:sha-086f323
          command: [ "python", "insert-build-plugin.py", "qmstr-maven-plugin.xml" ]
          volumeMounts:
            - name: buildroot-volume
              mountPath: /home/configure/buildroot
      volumes:
        - name: buildroot-volume
          emptyDir: { }
        - name: config-volume
          configMap:
            name: qmstr-config
            items:
              - key: qmstrConfig
                path: qmstr.yaml

