name: Package and deploy snapshot of 'eu.fasten.{parent, core}'

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of distributionManagement/repository/id
          settings-path: ${{ github.workspace }} # location of settings.xml
      
      - run: mvn -B -ntp clean deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
